// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMkkGeYdJb-TvozXHMIJz8XReoxuKHq4',
    appId: '1:998255141329:web:5cb6c9f3c7c09d142bc0f0',
    messagingSenderId: '998255141329',
    projectId: 'mariavaicomoutras-e7c28',
    authDomain: 'mariavaicomoutras-e7c28.firebaseapp.com',
    storageBucket: 'mariavaicomoutras-e7c28.firebasestorage.app',
    measurementId: 'G-22GV633E3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFD-dvwvg6XEwT5ZI3vVpMsQHYZ6RsQzo',
    appId: '1:998255141329:android:cf7a9a05830e94c52bc0f0',
    messagingSenderId: '998255141329',
    projectId: 'mariavaicomoutras-e7c28',
    storageBucket: 'mariavaicomoutras-e7c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsKAI4hg4t_wIS8irHe0hj6udBwm7XKoU',
    appId: '1:998255141329:ios:59c1f2bc5590274a2bc0f0',
    messagingSenderId: '998255141329',
    projectId: 'mariavaicomoutras-e7c28',
    storageBucket: 'mariavaicomoutras-e7c28.firebasestorage.app',
    iosBundleId: 'com.mariavai.mariavaiservices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopment',
    appId: '1:123456789:macos:abcdef',
    messagingSenderId: '123456789',
    projectId: 'mariavaicomoutras-e7c28',
    storageBucket: 'mariavaicomoutras-e7c28.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopment',
    appId: '1:123456789:windows:abcdef',
    messagingSenderId: '123456789',
    projectId: 'mariavaicomoutras-e7c28',
    storageBucket: 'mariavaicomoutras-e7c28.appspot.com',
  );
}